### ISSUE TITLE
Any plans to do a cross blockchain decentralised exchange?

### ISSUE THREAD

**Issue by James-Sangalli** [0xProject/ZEIPs#21]
We all know it is easier to pull this off with ethereum tokens and ether but what about with other chains like Bitcoin?

How would that work?

**Comment by AusIV** [comment]
Cross blockchain trading is theoretically possible using state channels that enable atomic swaps, but that's a very different paradigm than 0x implements. 0x allows makers to "fire and forget" orders, letting the relayers take care of connecting orders with takers, then the maker can be offline as the trade happens. Atomic swaps would require both parties to a trade to be online at the same time to execute the swap.

Another possible paradigm would be to have two-way-pegged tokens across chains. This is a concept that has already been proven for EVM chains by [PeaceRelay](https://github.com/KyberNetwork/peace-relay). Essentially it requires both chains to get the block headers from the other chain, so that merkle proofs can be used to establish that a particular action has been taken on the other chain. That could potentially allow say, the Ethereum blockchain to have ETC as an ERC20 token, while the Ethereum Classic blockchain has ETH as an ERC20 token. The ERC20 tokens could be traded via 0x exchanges on either contract, then redeemed for their respective tokens on the original chain.

This is doable (but expensive in gas terms) on EVM block chains. For non-EVM chains, it's possible to do one-way pegs. For example, there's a project called [BTCRelay](https://github.com/ethereum/btcrelay) which, for a while, was posting BTC block headers to an Ethereum contract. In that case, it would be possible to prove to an Ethereum contract that something had been done on the Bitcoin blockchain. That could allow you to create an ERC20 token that represented burned BTC, for example. But bitcoin doesn't have the necessary mechanisms to support proving to a BTC transaction that something had happened on the Ethereum blockchain, so there would be no way to redeem those ERC20 tokens for BTC back on the original chain.

The Rootstock blockchain uses a trusted group called [The Federation](https://en.wikipedia.org/wiki/RootStock#Federation) to allow transfer of BTC to their blockchain, but at this point the two way peg requires a trusted group. Something similar could be done on the Ethereum blockchain - essentially have a trusted group of signatories receive payments on other chains, issue tokens on Ethereum, and allow people to redeem the Ethereum tokens for the coins from the other chains. Those Ethereum tokens could be traded on the Ethereum blockchain, but you still have the problem of coming up with a trusted group to act as signatories.

**Comment by abandeali1** [comment]
In the future these questions are probably best for the forum at forum.0x.org. Let's keep issues and PRs in this repo to concrete proposals.
