### ISSUE TITLE
Cross-relayer orders

### ISSUE THREAD

**Issue by abandeali1** [0xProject/ZEIPs#3]
**Motivation:**
As is, a market maker must consciously decide on a specific `feeRecipient` for each order. This makes it difficult to broadcast a single order over multiple relayers without risking an overfill. A trader could post an order with the same parameters on different relayers, but since the orders have unique hashes, they are still all able to be filled. It is likely that relayers end up broadcasting orders from other relayers in an attempt to aggregate liquidity and attract traders, but then the relayers are not necessarily being fairly compensated for their storage and bandwidth.

**Proposed Solution:**
By tweaking how the `orderHash` is calculated, we can allow for a single order to specify multiple `feeRecipients` with different fee parameters. 

Currently, `orderHash` is calculated as:

```
keccak256(exchangeContractAddress, maker, taker, makerToken, takerToken, feeRecipient, makerTokenAmount, takerTokenAmount, makerFee, takerFee, expirationTimestampInSec, salt)
```

We can instead separate the fee parameters and calculate `orderHash` as follows:

```
keccak256(exchangeContractAddress, maker, taker, makerToken, takerToken, makerTokenAmount, takerTokenAmount, expirationTimestampInSec, salt)
```

Now, instead of signing `orderHash` to validate an order, we instead sign:

```
keccak256(orderHash, feeRecipient, makerFee, takerFee)
```

When an order is filled or cancelled, the `filled` and `cancelled` mappings still update values for the given `orderHash`. This allows a trader to submit the same order to multiple relayers with individual fee specifications without risking an overfill, and relayers can compete to get a single order filled.

**Potential Issues:**
- Due to network latency, this scheme would increase the probability of traders accidentally attempting to fill the same order as another trader using a different relayer.
- This could allow traders to bypass relayers, who have spent money on storage and bandwidth. A `taker` could receive an order from a relayer, contact the order `maker`, and fill that same order with no fees and a new signature.

**Comment by fabioberger** [comment]
Although it's cumbersome, I thought I'd still mention that another way to solve the "over fill" issue today is to create an order from an address with exactly `makerTokenAmount` tokens. This way, there is no way the order can be overfilled, and the multiple orders on relayers will be pruned from their orderbook once they check whether the order is still fillable and realize there are no longer sufficient backing tokens.

**Comment by fabioberger** [comment]
@abandeali1 can you elaborate on potential issue #1?

**Comment by PhABC** [comment]
From what I understand from issue 1, encouraging users to post on multiple relayers will increase the odds of "fillOrder" collision between traders. I think this is a problem we will face regardless of this change since our goal is to encourage relayers from sharing their orders with one another. I personally believe we should embrace this shared liquidity and find other solutions to reduce fillOrder collisions. 

Perhaps second-order relayers (the ones borrowing orders from another) could send an event message when one of their users fill an order from a first order relayer, and first order relayer could update it's orderbook. Other second order relayers will need to do API calls more frequently. Second-order relayers that don't send these events could have their API access restricted by first-order relayers and first-order relayers that don't take into considerations will lose interest from second-order relayers, since it degrades their users experience.
